FROM node:22.14.0-alpine

RUN corepack enable && corepack prepare pnpm@10.6.0 --activate

WORKDIR /app

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev"]