services:
  postgres:
    image: postgres:17-alpine
    container_name: bookbridge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bookbridgeuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bookbridgepassword}
      POSTGRES_DB: ${POSTGRES_DB:-bookbridgedb}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bookbridgeuser} -d ${POSTGRES_DB:-bookbridgedb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: bookbridge-nextjs
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER:-bookbridgeuser}:${POSTGRES_PASSWORD:-bookbridgepassword}@postgres:5432/${POSTGRES_DB:-bookbridgedb}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret}
    depends_on:
      postgres:
        condition: service_healthy
    command: pnpm dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: bookbridge-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@bookbridge.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: